### ISSUE TITLE
Transaction details for missing transaction exposes internal details

### ISSUE THREAD

**Issue by m4ktub** [Bitcoin-com/rest.bitcoin.com#354]
If you request the transaction details of a transaction that does not exist the REST API responds with an HTTP 500 error and a lot of internal details.

Example:
https://rest.bitcoin.com/v2/transaction/details/3086defc6ddda41c4b4bab898966ad517a6487749499ed01ba88be78c56e5ae7

Result:
```
{ Error: Request failed with status code 404
    at createError (/var/www/rest.bitcoin.com/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/www/rest.bitcoin.com/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/var/www/rest.bitcoin.com/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: [Object],
     transformResponse: [Object],
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: [Object],
     method: 'get',
     url:
      'http://194.14.247.150/api/tx/3086defc6ddda4144b4bab898966ad517a6487749499ed01ba88be78c56e5ae7',
     data: undefined },
  request:
   ClientRequest {
     _events: [Object],
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: [Socket],
     connection: [Socket],
     _header:
      'GET /api/tx/3086defc6ddda4144b4bab898966ad517a6487749499ed01ba88be78c56e5ae7 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: 194.14.247.150\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: [Agent],
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/api/tx/3086defc6ddda4144b4bab898966ad517a6487749499ed01ba88be78c56e5ae7',
     _ended: true,
     res: [IncomingMessage],
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: [Writable],
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]: [Object] },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers: [Object],
     config: [Object],
     request: [ClientRequest],
     data: 'Not found' } }
```

**Comment by christroutner** [comment]
Closing this issue as it's the same issue covered in Issue #300. A fix has been implemented and will be rolled out to production shortly.
